version: "3.7"
services:
  app:
    container_name: app
    restart: always
    image: adaptive-cram-dev:v0.1.1
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/data/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      FLASK_ENV: development
      MONGO_URL: mongodb://127.0.0.1:27017