version: "3.7"
services:
  app:
    container_name: app
    restart: always
    image: adaptive-cram-dev
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/dev/cfs/data/db:/data/db
    ports:
      - "27017:27017"
    # command: mongod --bind_ip_all
# volumes:
#   ~/dev/cfs/data/mongo:
    # links:
    #   - mongo
    # environment:
    #   WAIT_HOSTS: mongo:27017
  